import Foundation
import Testing
@testable import LingxiCore

struct ReferenceSkillsFixtureTests {
    private struct Fixture: Decodable {
        let cases: [Case]
        struct Case: Decodable {
            let id: String
            let instant: String
            let timeZone: String
            let dayBoundary: BirthDayBoundary
            let pillars: [String: String]
        }
    }

    /// Golden facts are generated by the user's actual Python skill engines.
    /// This test is fully offline and does not require their unbundled source.
    @Test func nativeChartsMatchEightReferenceCasesAndBothDayBoundaries() throws {
        let fixtureURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("Fixtures/reference-four-pillars.json")
        let fixture = try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: fixtureURL))
        #expect(fixture.cases.count == 8)
        let engine = FourPillarsEngine()
        for item in fixture.cases {
            let instant = try #require(ISO8601DateFormatter().date(from: item.instant))
            let timeZone = try #require(TimeZone(identifier: item.timeZone))
            let chart = try engine.chart(at: instant, timeZone: timeZone, dayBoundary: item.dayBoundary)
            let actual = ["year": chart.year.text, "month": chart.month.text,
                          "day": chart.day.text, "time": try #require(chart.hour).text]
            #expect(actual == item.pillars, "Reference case: \(item.id)")
        }
    }
}
